prac/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'sessions/create'

  get 'sessions/destroy'
  get 'article/search'
  devise_for :users
  resource :articles do 
    get "userarticles"
  end
  get 'articles/index'  
   resources :articles do 
    resources :comments
    resources :sections
      end

resources :favorites, only: [:create, :destroy]
  get "/auth/:provider/callback", to: "githubsessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'githubsessions#destroy', as: 'signout'
  root to: 'articles#index'

end

prac/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :sections
	belongs_to :category
	accepts_nested_attributes_for :sections, allow_destroy: true

	validates :user_id, presence: true
	validates :title, presence: true, length: {minimum: 5}
def self.search(search)
  if search
    where('text LIKE ?', "%#{search}%")
  else
  	Article.all
  end
end
end

prac/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    load_and_authorize_resource

    def index 
     @article = Article.search(params[:search])
  end

  def show
  end

  def new
    @categories = Category.all.map{ |cat| [cat.name, cat.id] }
  end

  def create
    @article.category_id = params[:category_id]
    @article.user = current_user
    respond_to do |format| 
      if @article.save 

        format.html { redirect_to @article, notice: 'Product was successfully created.' } 
        format.json { render :show, status: :created, location: @article } 
      else 
        format.html { render :new } 
        format.json { render json: @article.errors, status: :unprocessable_entity } 
      end 
    end 
  end

  def search
  @article = Article.search(params[:search].split("=").last)
  respond_to :js
  end

  def edit
    @categories = Category.all.map { |cat| [cat.name, cat.id] }
    if @article.user_id != current_user.id
      redirect_to article_path, notice: "You do not have permission to edit this article"
    else
      flash[:notice] ="Edited successfully" 
    end
  end

  def userarticles
    @article = Article.all
  end

  def update
    @article.category_id = params[:category_id]
    if @article.update(article_params)
      flash[:notice] = "Article successfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.user_id == current_user.id
      @article.destroy
      redirect_to root_path
    end
  end

private
  def article_params
    params.require(:article).permit(:title , :text , sections_attributes: [:id , :body, :_destroy])
  end


end

prac/app/views/articles/_articles.html.erb
<% @article.each do |article| %>
  <div class="index_heading" ><%= link_to article.title , article_path(article)%> </div>
  <div id="index_value" >Author: <%= article.user.try(:username) %></div>
  <table>
    <div id="truncated_text"> <% if article.text.length > 150 %>
     <%= truncate_html(article.text, length: 150) %>
     <%= link_to '...Read more', article_path(article)%>

  <% else %>
    <%= article.text.html_safe %>
    </div>
<% end %>

<table>  
 <th><%= link_to '<button id="indexbtn" class="btn btn-info">Show</button>'.html_safe , article_path(article) %></th>
  <% if user_signed_in? && article.user_id == current_user.id %>
    <th><%= link_to '<button id="indexbtn" class="btn btn-warning">Edit</button>'.html_safe ,edit_article_path(article)%></th>
    <th><%= link_to '<button id="indexbtn" class="btn btn-danger">Delete</button>'.html_safe ,article_path(article), method: :delete, data: {confirm: 'are you sure?'}%></th>
  <%end%>
</table>
<hr/>
  <%end%>

prac/app/views/articles/_comments.html.erb
<h4> Comments : </h4>
<% @article.comments.each do |comment| %>
  <%if user_signed_in? && comment.user_id == @article.user_id %>
    <strong class="commenter">Author : </strong>
  <%elsif user_signed_in? && comment.user_id != @article.user_id || !user_signed_in? %>
    <strong class="commenter"><%= comment.user.username %></strong>

  <%end%>
  <div style="margin-bottom: 10px;width:85%;"><%= comment.body %></div>
  <hr/>
  <%if user_signed_in? && comment.user_id == current_user.id || user_signed_in? && @article.user_id == current_user.id %>
     <p id="comment_delete">  <%= link_to '<strong>Delete</strong>'.html_safe , [comment.article,comment],method: :delete, data: {confirm: 'are you sure?' }%>  </p>

  <% end %>
<% end %>

prac/app/views/articles/_form.html.erb
<%=tinymce %>
<%= nested_form_for @article do |form| %>
  <%  if @article.errors.any? %>
    <div id="error_explanation">
    <%= pluralize(@article.errors.count," error") %>
    probhited this article from being saved
    <ul>
    <% @article.errors.full_messages.each do |err| %>
      <li> <%=err %> </li>
    <%end%>
    </ul>
    </div>
  <%end%> 
    <%= form.label :category %><br>
  <%= select_tag(:category_id, options_for_select(@categories),:prompt => "Select one!" )%>
    or <%= link_to 'Add new Category' , new_category_path %><br>
    <hr></hr>
    <%= form.label :title%><br>
    <%= form.text_field :title, class: "form-control"%><br>
    <%= form.label :text  %><br>
    <%= form.text_area :text,class: "tinymce", id: 'edit_textbox'%>
    <%=form.fields_for :sections do |section_form|%>
    <%=section_form.text_area :body, class: "tinymce" %>
    <%= section_form.link_to_remove "Remove this Section" %>
    <% end %>
    <p><%= form.link_to_add "Add a Section", :sections %></p>

    <%= form.submit "Create Article" , class: "btn btn-primary", id: "submit_button"%> 
<% end %>

prac/app/views/articles/edit.html.erb
<h1> Editing Article </h1>
<%= render 'form' %>
<div id="back_button"><%= link_to '<button class="btn btn-primary">Back</button>'.html_safe , article_path%></div>

prac/app/views/articles/index.html.erb
<div id="user-widget">
  <% if user_signed_in? %>
  <p>
    Welcome, <%= current_user.username %>
  </p>
<%end%>
<div id="new_article"><%= link_to "<button class='btn btn-primary'>New Article</button>".html_safe, new_article_path %></div>
</div>

<% if user_signed_in? %>
  <strong style="position:relative;left:1000px">Your Favorites: </strong>
  <% Favorite.where(user_id: current_user.id).each do |favorite| %>
    <% @article.where(id:favorite.favorited_id).each do |fav_art| %>
      <div style="position:relative;left:1000px">
        <ul>
          <li>
            <%= link_to fav_art.title, article_path(fav_art) %>
          </li>
        </ul>
      </div>
    <%end%>
  <%end%>
<%end%>

<%= form_tag root_path, :method => 'get', :id => "articles_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] , class: "search_box" , placeholder: "search for article"%>
    </p> 
  <div id="articles"><%= render 'articles' %></div>
<% end %> 
    

    

prac/app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render("articles")) %>");

prac/app/views/articles/new.html.erb
<h1> Add new article </h1>
<%= render 'form' %>
<%= link_to '<button class="btn btn-primary">Back</button>'.html_safe , root_path %>

prac/app/views/articles/search.js.erb
	$(".article_tbody_content").html("<%= escape_javascript render('articles') %>");

prac/app/views/articles/show.html.erb
<% @category = Category.where(id: @article.category_id) %>
<% @section  = Section.where(article_id: @article.id) %>
<div id="everything">
  <h1 id="article_heading"><%= @article.title %></h1>
  <div id="author">By <%=@article.user.username%> on <%= @article.created_at.strftime("%d-%m-%Y")%> 
    <% if @article.category_id != nil %> 
    , Category: <%= link_to @category.first.name, category_path(@category.first.id) %>
    <% end %>
  </div>

  <%= @article.text.html_safe %>
  <% @section.each do |section| %>
  <%=section.body.html_safe%>
   <% end %>
    
  <%=render 'comments' %>

 
  <%if user_signed_in? %>
    <div id="comment_plus_button">
      <div id="comment_box" class="well"> 
        <h2> Add comments </h2>
        <%= form_for([@article, @article.comments.build]) do |f| %>
          <p>
            <%= f.label 'Commenting as '%>
            <strong><%= current_user.username %></strong>
          </p>
          <p>
            <%=f.label :body %><br>
            <%= f.text_area :body, class:'form-control'%>
          </p>
          <p>
            <%= f.submit "Create Comment", class:'btn btn-primary'%>
          </p>
      </div>
          <div id="show_and_edit"> 
            <% if user_signed_in? && @article.user_id == current_user.id %>
              <%= link_to '<button class="btn btn-primary">Edit</button>'.html_safe , edit_article_path(@article) %>
            <%end%>
            <%= link_to '<button class="btn btn-primary">All</button>'.html_safe , articles_path %></p>
            <%- unless current_user.favorite_articles.exists?(id: @article.id) -%>
              <%= link_to '<button class="btn btn-success">Add to Favorite</button>'.html_safe, favorites_path(article_id: @article), method: :post %>
            <%-else-%>
              <%= link_to '<button class="btn btn-danger">Remove from favorite</button>'.html_safe, favorite_path(@article), method: :delete %>
            <%-end-%>
        <%end%>
<%end%>

  </div>
</div>
</div>

prac/app/views/articles/userarticles.html.erb
<h4> <%= current_user.username%>'s Articles</h4>
<ul>
<% @article.where(user_id:current_user.id).each do |a| %>
<li class="user_articles"><%=link_to a.title, article_path(a)%></li> 
<%end%>
</ul>