prac/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'sessions/create'

  get 'sessions/destroy'
  get 'article/search'
  devise_for :users
  resource :articles do 
    get "userarticles"
  end
  get 'articles/index'  
   resources :articles do 
    resources :comments
    resources :sections
      end

resources :favorites, only: [:create, :destroy]
  get "/auth/:provider/callback", to: "githubsessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'githubsessions#destroy', as: 'signout'
  root to: 'articles#index'

end

prac/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
	validates :name, presence: true, length: {minimum: 3}
end

prac/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

prac/app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

prac/app/views/categories/edit.html.erb
<% Article.where(category_id: @category.id).each do |article| %>
<% if user_signed_in? && current_user.id == article.user_id%>
<h1> Editing category </h1>

<%= render 'form' %>

<%= link_to '<button class="btn btn-primary">Show</button>'.html_safe, @category %>
<% else %>
<h1><%= flash[:notice] = "Cannot Edit this Category" %><h1><br>
<%end%>
<%= link_to '<button class="btn btn-primary">Back</button>'.html_safe, categories_path %>
<% end %>

prac/app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th <h4>Name</h4>
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = link_to '<button class="btn btn-primary">Show</button>'.html_safe, category
        td = link_to '<button class="btn btn-warning">Edit</button>'.html_safe, edit_category_path(category)
        td = link_to '<button class="btn btn-danger">Delete</button>'.html_safe, category, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to '<button class="btn btn-primary">New Category</button>'.html_safe, new_category_path

prac/app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

prac/app/views/categories/show.html.erb
<h1>Articles under <%= @category.name %> are : <h1><br>
<% Article.where(category_id: @category.id).each do |article| %>
  <h4><li><%= link_to article.title , article_path(article) %></li><h4>
<% end %>
  <%= link_to '<button class="btn btn-primary">Back</button>'.html_safe, categories_path %>